include:
  - project: 'spkumar17/gitlab-templates'
    file: 'Trivy-file-scan-Template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Trivy-imagescan-Template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Sonarscanner-template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Docker-Build-Template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Docker-Push-Template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Nodejs-build-template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Nodejs-test-template.yml'
    ref: 'main'


stages:
  - build
  - test
  - security_stage
  - Docker_Build
  - image_security
  - Docker_push

variables:
  venv_Dir: "$CI_PROJECT_DIR/src/currencyservice"
  REGISTRY_IMAGE: "Microserviceimage"
  SERVICE_NAME: "currencyservice"
  
before_script:
  - echo "Running before script for currencyservice"
  - cd src/currencyservice/
  - ls -la

currencyservice_build:
  extends: .build_python_template
  stage: build
  # tags:
  #   - Runner1

currencyservice_test:
  extends: .Test_python_template
  stage: test
  # tags:
  #   - Runner1

currencyservice_trivy_file_scan:
  extends: .trivy-filescan
  stage: security_stage
  # tags:
  #  - Runner1

# currencyservice_sonar_scan:
#   extends: .sonarqube-check-template
#   stage: security_stage
#   dependencies:
#     - currencyservice_build
#   tags:
#     - Runner1

# currencyservice_docker_build:
#   extends: .docker_build_template
#   stage: Docker_Build
#   dependencies:
#     - currencyservice_build
#   tags:
#     - shellrunner

# currencyservice_trivy_image_scan:
#   extends: .trivy-imagescan
#   stage: image_security
#   dependencies:
#     - currencyservice_docker_build
#   tags:
#   - Runner1

# currencyservice_docker_push:
#   extends: .docker_push_template
#   stage: Docker_push
#   dependencies:
#     - currencyservice_docker_build
#   tags:
#     - shellrunner    
            