include:
  - project: 'spkumar17/gitlab-templates'
    file: 'Trivy-file-scan-Template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Trivy-imagescan-Template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Sonarscanner-template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Golang-Test-template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Golang-build-template.yml'
    ref: 'main'    
  - project: 'spkumar17/gitlab-templates'
    file: 'Docker-Build-Template.yml'
    ref: 'main'
  - project: 'spkumar17/gitlab-templates'
    file: 'Docker-Push-Template.yml'
    ref: 'main'


stages:
  - build
  - test
  - security_stage
  - Docker_Build
  - image_security
  - Docker_push

variables:
  REGISTRY_IMAGE: "Microserviceimage"
  SERVICE_NAME: "frontend"
  

before_script:
  - echo "Running before script for frontend"
  - cd src/frontend/
  - ls -la

frontend_build:
  extends: .golang_build_template
  stage: build
  # tags:
  #   - Runner1
  
# frontend_test:
#   extends: .golang_test_template
#   stage: test
#   # tags:
#   #   - Runner1

# frontend_trivy_file_scan:
#   extends: .trivy-filescan
#   stage: security_stage
#   # tags:
#   #  - Runner1

# frontend_sonar_scan:
#   extends: .sonarqube-check-template
#   stage: security_stage
#   dependencies:
#     - frontend_build
#   # tags:
#   #   - Runner1


# frontend_docker_build:
#   extends: .docker_build_template
#   stage: Docker_Build
#   dependencies:
#     - frontend_build
#   tags:
#     - shellrunner

# frontend_trivy_image_scan:
#   extends: .trivy-imagescan
#   stage: image_security
#   dependencies:
#     - frontend_docker_build
#   # tags:
#   # - Runner1

# frontend_docker_push:
#   extends: .docker_push_template
#   stage: Docker_push
#   dependencies:
#     - frontend_docker_build
#   tags:
#     - shellrunner