# name: Trigger GitLab CI Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   trigger:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger GitLab Pipeline
#         run: |
#           curl -X POST \
#             -F token=${{ secrets.GITLAB_TIGGERTOKEN }} \
#             -F ref=main \
#             https://gitlab.com/api/v4/projects/71957264/trigger/pipeline
